### PR TITLE
feat: Add ability to add creators to cNFTs

### PR DESCRIPTION
**Pull request by ChewingGlass**

### CODE REVIEW

**Comment by samwise2** [comment]
I'm not sure if this is still being worked on, but this seems like it may be a subset of https://github.com/metaplex-foundation/mpl-bubblegum/pull/3.

**Comment by ChewingGlass** [comment]
> I'm not sure if this is still being worked on, but this seems like it may be a subset of #3.

It is def a subset. Is #3 getting done? If so can close this

**Comment by samwise2** [comment]
> > I'm not sure if this is still being worked on, but this seems like it may be a subset of #3.
> 
> It is def a subset. Is #3 getting done? If so can close this

Yup, it was parked for a bit but MPL should be reviewing now :)

**Comment by danenbm** [comment]
> > > I'm not sure if this is still being worked on, but this seems like it may be a subset of #3.
> > 
> > 
> > It is def a subset. Is #3 getting done? If so can close this
> 
> Yup, it was parked for a bit but MPL should be reviewing now :)

Yes we are reviewing #3 right now.

**Comment by danenbm** [comment]
Merged and deployed long ago in https://github.com/metaplex-foundation/mpl-bubblegum/pull/3

**Pull request closed without merging**
